name: Expo Build Workflow

on:
  push:
    branches:
      - master # Defina a branch que você deseja acionar o workflow

jobs:
  expo_build:
    runs-on: ubuntu-latest

    env:
      EAS_EMAIL: ${{ secrets.EAS_EMAIL }}
      EAS_PASSWORD: ${{ secrets.EAS_PASSWORD }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install Eas CLI
        run: npm install -g eas-cli

      - name: Log in to Eas
        run: |
          eas login --email lucaslimabaseo@gmail.com --password Rammstein123@#

      - name: Build for Expo
        run: |
          eas build --platform android --profile preview
