name: Expo Build Workflow

on:
  push:
    branches:
      - master # Defina a branch que você deseja acionar o workflow

jobs:
  expo_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install Eas CLI
        run: npm install -g eas-cli

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Log in to Expo
        run: |
          expo login -u lucaslimabaseo@gmail.com -p Rammstein123@#
          expo whoami

     - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: yarn install

      - name: Create preview
        uses: expo/expo-github-action/preview@v8
        with:
          command: eas update --auto