name: Expo Build Workflow

on:
  push:
    branches:
      - master # Defina a branch que você deseja acionar o workflow

jobs:
  expo_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install Eas CLI
        run: npm install -g eas-cli

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Log in to Expo
        run: |
          expo login -u lucaslimabaseo@gmail.com -p Rammstein123@#
          expo whoami

      - name: Build for Expo
        run: |
          eas build --platform android --profile preview
